### ISSUE TITLE
Most of the links in roadmap don't work

### ISSUE THREAD

**Issue by xevg** [finos/zenith#137]
### Steps to Reproduce:
Click a link on any doc in the roadmap section. The link for the meetings don't work either. 

### Expected Result:
The documents in the link

### Actual Result:
Error message 

### Environment:
...version and build of the project, OS and runtime versions, virtualised environment (if any), etc. ...

### Additional Context:
...add any other context about the problem here. If applicable, add screenshots to help explain...

**Comment by padraignix** [comment]
Thanks for reaching out @xevg! Can you provide an example of what type of link isn't working? I tried the various links under roadmap and wasn't seeing any issues. Example:

https://zenith.finos.org/docs/roadmap/roadmap-braintrust

**Comment by psmulovics** [comment]
I went through every link and checked whether docosaurus's link checker is working (it does), so, @xevg , can you please provide some more info?
